### ISSUE TITLE
Simple skeleton Python/Go server

### ISSUE THREAD

**Issue by stanlyzoolo** [balena-io-examples/balena-go-hello-world#10]
On this wonderful Friday morning, I was scrolling through cool projects from the Balena team and noticed an inaccuracy in the description of the project [balena-go-hello-world](https://hub.balena.io/organizations/gh_vipulgupta2048/fleets/balena-go-hello-world) ^_^
I think you meant Go server instead of Python.

Good luck in your work and please with new ideas!)

**Comment by vipulgupta2048** [comment]
Thanks @stanlyzoolo for reaching out this is very much appreciated. We are in process of upgrading our [getting started guides](https://www.balena.io/docs/learn/getting-started/raspberrypi3/nodejs/) and the examples. In the mix of making 7 similar PR's to 7 different repos, I must have mixed this up. 

For your context, this description is coming from the file https://github.com/balena-io-examples/balena-go-hello-world/blob/master/balena.yml and a change here will instantly get reflected on balenahub when the fleet is pushed next. I will do the needful. Feel free to suggest more improvements.
